
!! Third party JS :
<script src="$dirjs/js_tools/katex/katex.min.js"></script>

<script src="$dirjs/js_tools/quill/highlight.js-master/src/highlight.js"></script>
<script src="$dirjs/js_tools/quill/quill.min.js"></script>

<script src="$dirjs/js_tools/html2canvas.js"></script>

<script src="$dirjs/js_tools/blockly/blockly_compressed.js"></script>
<script src="$dirjs/js_tools/blockly/blocks_compressed.js"></script>

!! Translation files :
<script src="$dirjs/js_tools/blockly/msg/js/$lang.js" charset="utf-8"></script>
<script src="$dirjs/src/BlocklyWIMS/msg/js/$lang.js" charset="utf-8"></script>

!! Main JS :
<script src="$dirjs/laruche.min.js" charset="utf-8"></script>
