!if $httpd_HTTP_X_REQUESTED_WITH!=$empty
  !changeto msg.phtml
!endif

!read names-$lang.phtml
!set dirjs=scripts/js/laruche

!set wims_html_header=!append line \
  <!-- Foundation 6 styles -->\
  <!-- <link rel="stylesheet" href="themes/_css/foundation_forms.css"/> -->\
  <!-- <link rel="stylesheet" href="themes/_css/foundation_card.css"/> -->\
  <!-- <link rel="stylesheet" href="themes/_css/foundation_callout.css"/> -->\
  <!-- <link rel="stylesheet" href="themes/_css/foundation_grid_float.css"/> -->\
  <link rel="stylesheet" href="themes/_css/foundation.min.css"/>\
  <link rel="stylesheet" href="themes/_css/foundation-icons/foundation-icons.css"/>\
  <link rel="stylesheet" href="$dirjs/css/ruche.css"/>\
  <!-- Style sheets of tools for the Quill editor -->\
  <link rel="stylesheet" href="$dirjs/js_tools/katex/katex.min.css" />\
  <link rel="stylesheet" href="$dirjs/js_tools/quill/highlight.js-master/src/styles/atom-one-light.css" />\
  <!-- Customized style sheet of Quill -->\
  <link rel="stylesheet" href="$dirjs/js_tools/quill/quill.snow-custom.css" />\
to $wims_html_header

!header

!! Contenu du module par ici.

!if $compute=yes
 !if $error!=$empty
  <div class="wims_alertmsg">
  !read msg.phtml
  </div>
  !read menu.phtml
  !goto end
 !else
  !read answer.phtml
 !endif
!else
 !! put some explanations here.
 !read menu.phtml
!endif compute=yes?


:end

!read footer.phtml

!set wims_menu_items=!append line modtool,1,module=adm/modtool\
  to $wims_menu_items

!tail
