!read adm/language lang/names.phtml
!set dirjs=scripts/js/laruche

!if $httpd_HTTP_X_REQUESTED_WITH!=$empty
  !changeto json.phtml
!endif

!set wims_html_header=!append line \
  <!-- Foundation 6 styles -->\
  <link rel="stylesheet" href="themes/_css/foundation_forms.css"/>\
  <link rel="stylesheet" href="themes/_css/foundation_card.css"/>\
  <link rel="stylesheet" href="themes/_css/foundation_callout.css"/>\
  <link rel="stylesheet" href="themes/_css/foundation_grid_float.css"/>\
  <!--link rel="stylesheet" href="themes/_css/foundation.min.css"/-->\
  <!--link rel="stylesheet" href="themes/_css/foundation-icons/foundation-icons.css"/-->\
  <link rel="stylesheet" href="$dirjs/css/ruche.css"/>\
  <!-- Style sheets of tools for the Quill editor -->\
  <link rel="stylesheet" href="$dirjs/js_tools/katex/katex.min.css" />\
  <link rel="stylesheet" href="$dirjs/js_tools/quill/highlight.js-master/src/styles/atom-one-light.css" />\
  <!-- Customized style sheet of Quill -->\
  <link rel="stylesheet" href="$dirjs/js_tools/quill/quill.snow-custom.css" />\
to $wims_html_header

!set module_title=<img src="$dirjs/images/logo.png" alt="La Ruche">
!header

!! Contenu du module par ici.

!if $compute=yes
  !if $error!=$empty
    !read msg.phtml
  !else
    !read answer.phtml
  !endif
!else
  <div class="popup_hidden" id="popup"></div> <!-- va servir pour tous les popups -->
 !if $job=sendfile
    !read sendfile.phtml
 !else
    <div class="row">
      !set wims_ref_class=wims_button
      !href module=$module&job=sendfile TEST AJAX
    </div>
    !read menu.phtml
    !read footer.phtml
  !endif
!endif

!set wims_menu_items=!append line laruche,1,module=adm/tool/laruche\
  to $wims_menu_items
!set wims_menu_items=!append line modtool,1,module=adm/modtool\
  to $wims_menu_items
!set wims_menu_items=!append line createxo,1,module=adm/createxo\
  to $wims_menu_items

!tail
