<!-- Automatically generated by bin/oefdoc.pl -->
var anstypename='Types de réponses';
var anstype = [ 'algexp','aset','atext','case','checkbox','chembrut','chemclick','chemdraw','chemeq','chessgame','chset','click','clickfill','clicktile','compose','coord','correspond','crossword','default','dragfill','draw','equation','flashcard','formal','fset','function','geogebra','javacurve','jmolclick','jsxgraph','jsxgraphcurve','keyboard','litexp','mark','matrix','menu','multipleclick','nocase','numeric','numexp','puzzle','radio','range','raw','reorder','set','sigunits','symtext','units','vector','wlist' ];
function anstypefun(instruction){
    switch(instruction)
	{
	case 'menu' :
chaine_aide='<div class="title">menu</div>'+
'<div class="explication"><div class="title">Explication</div>réponse à choix multiples\
 </div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,multiple">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'wlist' :
chaine_aide='<div class="title">wlist</div>'+
'<div class="explication"><div class="title">Explication</div>Liste de mots \
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,wlist">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'click' :
chaine_aide='<div class="title">click</div>'+
'<div class="explication"><div class="title">Explication</div>réponse à choix multiples\
 </div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,multiple">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'symtext' :
chaine_aide='<div class="title">symtext</div>'+
'<div class="explication"><div class="title">Explication</div>Texte outil avancé d\'identification de textes\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,symtext">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'numexp' :
chaine_aide='<div class="title">numexp</div>'+
'<div class="explication"><div class="title">Explication</div>Nombre rationnel  la comparison se fait de façon formelle\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,numexp">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'default' :
chaine_aide='<div class="title">default</div>'+
'<div class="explication"><div class="title">Explication</div>Auto détermination automatique de certains types de base\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,default">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'checkbox' :
chaine_aide='<div class="title">checkbox</div>'+
'<div class="explication"><div class="title">Explication</div>réponse à choix multiples\
 </div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,multiple">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'jsxgraphcurve' :
chaine_aide='<div class="title">jsxgraphcurve</div>'+
'<div class="explication"><div class="title">Explication</div>Dessin utilisant JSXgraph  permettant des tracés avec des formes prédéfinies ou libres\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,jsxgraphcurve">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'crossword' :
chaine_aide='<div class="title">crossword</div>'+
'<div class="explication"><div class="title">Explication</div>Mots croisés\
 </div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,crossword">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'chset' :
chaine_aide='<div class="title">chset</div>'+
'<div class="explication"><div class="title">Explication</div>Ensemble de caractères \
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,chset">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'equation' :
chaine_aide='<div class="title">equation</div>'+
'<div class="explication"><div class="title">Explication</div>Equation numérique la comparaison se fait numériquement\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,equation">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'sigunits' :
chaine_aide='<div class="title">sigunits</div>'+
'<div class="explication"><div class="title">Explication</div>Nombre avec possibilité de demander une unité et un nombre de chiffres significatifs\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,sigunits">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'mark' :
chaine_aide='<div class="title">mark</div>'+
'<div class="explication"><div class="title">Explication</div>réponse à choix multiples\
 </div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,multiple">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'aset' :
chaine_aide='<div class="title">aset</div>'+
'<div class="explication"><div class="title">Explication</div>Ensemble fini avec une analyse textuelle ou numérique\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,set">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'chessgame' :
chaine_aide='<div class="title">chessgame</div>'+
'<div class="explication"><div class="title">Explication</div>Déplacement de pièces sur un échiquier\
 </div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,chessgame">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'chemeq' :
chaine_aide='<div class="title">chemeq</div>'+
'<div class="explication"><div class="title">Explication</div>Equation chimique avec analyse d\'équilibre\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,chemeq">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'formal' :
chaine_aide='<div class="title">formal</div>'+
'<div class="explication"><div class="title">Explication</div>Expression mathématique comparaison formelle\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,exp">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'radio' :
chaine_aide='<div class="title">radio</div>'+
'<div class="explication"><div class="title">Explication</div>réponse à choix multiples\
 </div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,multiple">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'keyboard' :
chaine_aide='<div class="title">keyboard</div>'+
'<div class="explication"><div class="title">Explication</div>Texte  tapé à partir du clavier proposé\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,keyboard">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'javacurve' :
chaine_aide='<div class="title">javacurve</div>'+
'<div class="explication"><div class="title">Explication</div>Dessin utilisant Java  permettant des tracés avec des formes prédéfinies ou libres\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,javacurve">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'reorder' :
chaine_aide='<div class="title">reorder</div>'+
'<div class="explication"><div class="title">Explication</div>Mise en ordre  d\'une liste d\'objets\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,reorder">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'range' :
chaine_aide='<div class="title">range</div>'+
'<div class="explication"><div class="title">Explication</div>Nombres dans une zone tout ce qui est dans la zone est accepté\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,range">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'jmolclick' :
chaine_aide='<div class="title">jmolclick</div>'+
'<div class="explication"><div class="title">Explication</div>Clic sur des atomes en 3D  nécessite l\'applet Jmol\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,jmolclick">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'jsxgraph' :
chaine_aide='<div class="title">jsxgraph</div>'+
'<div class="explication"><div class="title">Explication</div>Géométrie dynamique utilisation de l\'applet JSXGraph\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,jsxgraph">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'case' :
chaine_aide='<div class="title">case</div>'+
'<div class="explication"><div class="title">Explication</div>Texte des mots ou des phrases\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,text">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'multipleclick' :
chaine_aide='<div class="title">multipleclick</div>'+
'<div class="explication"><div class="title">Explication</div>réponse à choix multiples\
 </div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,multiple">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'raw' :
chaine_aide='<div class="title">raw</div>'+
'<div class="explication"><div class="title">Explication</div>Texte brut  la comparaison se fait par des options\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,raw">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'dragfill' :
chaine_aide='<div class="title">dragfill</div>'+
'<div class="explication"><div class="title">Explication</div>Objets à glisser-déposer  qui peuvent être du texte</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,clickfill">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'fset' :
chaine_aide='<div class="title">fset</div>'+
'<div class="explication"><div class="title">Explication</div>Ensemble fini avec une analyse textuelle ou numérique\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,set">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'chemclick' :
chaine_aide='<div class="title">chemclick</div>'+
'<div class="explication"><div class="title">Explication</div>Sélectionner des atomes ou des liaisons d\'une molécule avec une applet Java\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,chemclick">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'nocase' :
chaine_aide='<div class="title">nocase</div>'+
'<div class="explication"><div class="title">Explication</div>Texte des mots ou des phrases\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,text">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'algexp' :
chaine_aide='<div class="title">algexp</div>'+
'<div class="explication"><div class="title">Explication</div>Expression mathématique comparaison formelle\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,exp">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'clicktile' :
chaine_aide='<div class="title">clicktile</div>'+
'<div class="explication"><div class="title">Explication</div>Mettre en couleur des pavés  nécessite java\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,clicktile">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'chemdraw' :
chaine_aide='<div class="title">chemdraw</div>'+
'<div class="explication"><div class="title">Explication</div>Dessiner une molécule avec une applet Java\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,chemdraw">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'numeric' :
chaine_aide='<div class="title">numeric</div>'+
'<div class="explication"><div class="title">Explication</div>Nombre la comparison se fait numériquement avec une précision fixée\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,numeric">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'litexp' :
chaine_aide='<div class="title">litexp</div>'+
'<div class="explication"><div class="title">Explication</div>Expression mathématique comparaison formelle\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,exp">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'vector' :
chaine_aide='<div class="title">vector</div>'+
'<div class="explication"><div class="title">Explication</div>Vecteur comparaison numérique des composantes\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,vector">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'coord' :
chaine_aide='<div class="title">coord</div>'+
'<div class="explication"><div class="title">Explication</div>Clic sur une image  dans une zone prédéfinie\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,coord">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'matrix' :
chaine_aide='<div class="title">matrix</div>'+
'<div class="explication"><div class="title">Explication</div>Matrice numérique  au sens mathématique ; la comparaison se fait numériquement coefficient par coefficient\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,matrix">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'function' :
chaine_aide='<div class="title">function</div>'+
'<div class="explication"><div class="title">Explication</div>Fonction numérique la comparaison se fait numériquement\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,function">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'correspond' :
chaine_aide='<div class="title">correspond</div>'+
'<div class="explication"><div class="title">Explication</div>Correspondance entre deux listes d\'objets\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,correspond">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'units' :
chaine_aide='<div class="title">units</div>'+
'<div class="explication"><div class="title">Explication</div>Nombre avec unité  pour la physique\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,units">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'chembrut' :
chaine_aide='<div class="title">chembrut</div>'+
'<div class="explication"><div class="title">Explication</div>Formule brute d\'une molécule en chimie\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,chembrut">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'clickfill' :
chaine_aide='<div class="title">clickfill</div>'+
'<div class="explication"><div class="title">Explication</div>Objets à glisser-déposer  qui peuvent être du texte</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,clickfill">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'geogebra' :
chaine_aide='<div class="title">geogebra</div>'+
'<div class="explication"><div class="title">Explication</div>Géométrie dynamique utilisation de l\'applet GeoGebra\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,geogebra">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'flashcard' :
chaine_aide='<div class="title">flashcard</div>'+
'<div class="explication"><div class="title">Explication</div>réponse à choix multiples\
 </div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,multiple">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'puzzle' :
chaine_aide='<div class="title">puzzle</div>'+
'<div class="explication"><div class="title">Explication</div>Reconstituer une image  présentée comme un puzzle\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,puzzle">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'atext' :
chaine_aide='<div class="title">atext</div>'+
'<div class="explication"><div class="title">Explication</div>Texte approximatif  la comparaison tolère les différences du type singulier/pluriel ...\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,atext">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'draw' :
chaine_aide='<div class="title">draw</div>'+
'<div class="explication"><div class="title">Explication</div> Dessin utilisant canvasdraw permettant des tracés (points  droites</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,draw">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'set' :
chaine_aide='<div class="title">set</div>'+
'<div class="explication"><div class="title">Explication</div>Ensemble fini avec une analyse textuelle ou numérique\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,set">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	case 'compose' :
chaine_aide='<div class="title">compose</div>'+
'<div class="explication"><div class="title">Explication</div>Composer en utilisant des composantes fournies\
</div>'+
'<a target="wims_help" href="wims.cgi?lang=fr&module=adm%2Fcreatexo&modtoolhelp=yes&+special_parm=reply,compose">++>></a>' ; return chaine_aide;
	   break;
	////******************** 

	
	}
}