<!-- Automatically generated by bin/oefdoc.pl -->
var oefcommandname= 'Instructions';
 var oefcommand= [ '\\title{  }', '\\language{  }', '\\author{  }', '\\email{  }', '\\format{  }', '\\css{  }', '\\precision{  }', '\\range{  }', '\\computeanswer{  }', '\\statement{  }', '\\answer{  }', '\\choice{  }', '\\condition{  }', '\\solution{  }', '\\hint{  }', '\\help{  }', '\\feedback{  }', '\\steps{  }', '\\nextstep{  }', '\\conditions{  }', '\\latex{  }', '\\credits{  }' ];
function oefcommandfun(instruction){
    switch(instruction)
	{
	case '\\title{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>définit le titre de l\'exercice</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\language{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>définit la langue de l\'exercice, comme <span class="tt wims_code_words">en</span> ou <span class="tt wims_code_words">fr</span></div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\author{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>définit l\'auteur de l\'exercice. Le mettre sous la forme <span class="tt wims_code_words">Prénom, Nom</span> (dans le cas de plusieurs auteurs, les séparer par des points-virgules).</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\email{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>définit l\'adresse électronique de l\'auteur (dans le cas de plusieurs auteurs, les séparer par une virgule).</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\format{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>format de l\'énoncé</div>'+
'<div class="explication"><div class="title">Explication</div> </div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\css{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>définit le style css</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\precision{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>précision en comparant la réponse de l\'utilisateur avec la solution. Donnez un nombre positif n ici&nbsp;: la comparaison sera effectuée avec une tolérance de 1/n.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\range{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>zone de variables pour l\'évaluation de fonction fournie par l\'utilisateur. Doit être donnée sous forme <span class="tt wims_code_words">n1..n2</span>, où n1 est le point de départ, n2 le point d\'arrivée.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\computeanswer{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>La commande <span class="tt wims_code_words">&#92;computeanswer{ no }</span> précise que l\'utilisateur doit lui-même faire les calculs et entrer la valeur finale. Si par contre, on met <span class="tt wims_code_words">&#92;computeanswer{ yes }</span>, l\'utilisateur peut entrer une formule comme <span class="tt wims_code_words">5*5</span>, laissant à l\'ordinateur le soin de faire les calculs.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\statement{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>le paramètre est l\'énoncé de l\'exercice</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\answer{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>définit une réponse libre. Le premier paramètre est le message pour la réponse, et le second est la bonne réponse. La réponse sera analysée selon des types (nombre, fonction, texte, etc).</div>'+
'<div class="explication"><div class="title">Explication</div>type option weight</div>'+
'<div class="explication"><div class="title">Explication</div>reorder shuffle nonstop</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\choice{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>définit un choix multiple. Le premier paramètre est le message pour le choix, le second les bons choix, et le troisième les mauvais choix. Les deux derniers paramètres peuveut (doivent) être une liste d\'objets séparés par des virgules. Il est permis d\'avoir plusieurs bons choix. Si un choix apparait à la fois comme bon et mauvais, il est pris pour bon.</div>'+
'<div class="explication"><div class="title">Explication</div>option weight</div>'+
'<div class="explication"><div class="title">Explication</div>shuffle noidontknow</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\condition{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>définit une condition spéciale pour l\'évaluation de réponses libres. Le premier argument est un texte qui sera affiché lors de l\'analyse de la réponse. Le second argument, on met la liste des conditions que la réponse de l\'utilisateur doit satisfaire pour être considérée comme bonne.	</div>'+
'<div class="explication"><div class="title">Explication</div>option weight</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\solution{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>donne une solution expliquée de l\'exercice. Le gestionnaire OEF peut décider de montrer la solution ou pas à l\'utilisateur, suivant le choix du niveau de difficulté pris par l\'utilisateur. Ne peut apparaître qu\'une seule fois dans un exercice.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\hint{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>donne une indication de l\'exercice. Le gestionnaire OEF peut décider de montrer l\'indication ou non, suivant le niveau de difficulté. Ne peut apparaître qu\'une seule fois dans un exercice.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\help{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>donne une aide à l\'exercice. Cette aide sera toujours accessible à l\'utilisateur, dans une fenêtre `popup\'. Ne peut apparaître qu\'une seule fois dans un exercice.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\feedback{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>affiche un commentaire quand la réponse tombe sous une certaine condition. Peut normalement être utilisé pour avertir d\'une erreur typique.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\steps{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>sert à définir les questions apparaissant à chaque étape ; doit être mis avant la commande <span class="tt wims_code_words">statement</span> (voir la variable <span class="tt wims_code_words">&#92;step</span>). Ne peut apparaître qu\'une seule fois dans un exercice.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\nextstep{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>sert à définir de manière dynamique les questions qui devront être posées ; doit être mis avant la commande <span class="tt wims_code_words">statement</span> (voir la variable <span class="tt wims_code_words">&#92;step</span>). Can be used only one time in the exercise. </div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\conditions{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>permet d\'indiquer les numéros des conditions utiles pour l\'exercice servant à contrôler les réponses de l\'utilisateur.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\latex{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>permet d\'écrire une version en latex de l\'exercice utilisant les variables définies dans l\'exercice et pouvant être téléchargées dans la version imprimable de l\'exercice (accessible uniquement par les développeurs ou les enseignants d\'une classe). Il est conseillé de mettre l\'énoncé dans un environnement latex prédéfini <span class="tt wims_code_words">&#92;begin{statement} &#92;end{statement}</span> et la solution dans l\'environnement  <span class="tt wims_code_words">&#92;begin{sol} ... &#92;end{sol}</span>.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\credits{  }' :
chaine_aide='<div class="explication"><div class="title">Explication</div>permet d\'inclure automatiquement un remerciement ou un crédit en fin d\'exercice (les variables sont évaluées). </div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	
	}
}