<!-- Automatically generated by bin/oefdoc.pl -->
var oefparm0name= 'Liste de types de variables';
 var oefparm0= [ '\\real{  =  }', '\\complex{  =  }', '\\text{  =  }', '\\integer{  =  }', '\\rational{  =  }', '\\function{  =  }', '\\matrix{  =  }' ];
function oefparm0fun(instruction){
    switch(instruction)
	{
	case '\\real{  =  }' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{x=random(-5..5)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>&#92;x est un nombre réel aléatoire entre -5 et 5</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\complex{  =  }' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;complex{z=(1+2*i)^3}</code></div>'+
'<div class="explication"><div class="title">Explication</div>&#92;z est le nombre complexe z=(1+2*i)^3</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\text{  =  }' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;text{a=1 2  3}</code></div>'+
'<div class="explication"><div class="title">Explication</div>&#92;a est le texte donné sans aucune transformation</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\integer{  =  }' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;integer{n=3*exp(&#92;a)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>&#92;n est l\'entier le plus proche de 3*e<sup>&#92;a</sup> (il dépend de la valeur de &#92;a)</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\rational{  =  }' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;rational{x=2*5/6}</code></div>'+
'<div class="explication"><div class="title">Explication</div>&#92;x est le nombre rationnel (exact) 5/3</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\function{  =  }' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;function{f=2*x^2}</code></div>'+
'<div class="explication"><div class="title">Explication</div>la fonction 2 x^2</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\matrix{  =  }' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;matrix{m=1,2,3<br/>4,5,6<br/>7,8,9}</code></div>'+
'<div class="explication"><div class="title">Explication</div>&#92;m est la matrice de 3 lignes et 3 colonnes. <br />&#92;m[ 2..-1;] revoie les lignes de &#92;m de 2 à la dernière ; <br />&#92;m[;2,3] renvoie les colonnes 2 et 3 de &#92;m.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	
	}
}