<!-- Automatically generated by bin/oefdoc.pl -->
var oefparm1name= 'Fonctions aléatoires';
 var oefparm1= [ 'random( .. )', 'randint( .. )', 'random( )', 'shuffle( )', 'shuffle( , )', 'randomitem( )', 'randitem( )', 'randomrow( )' ];
function oefparm1fun(instruction){
    switch(instruction)
	{
	case 'random( .. )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>random(-5..5)</code></div>'+
'<div class="explication"><div class="title">Explication</div>un nombre au hasard entre -5 et 5.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'randint( .. )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>randint(-5..5)</code></div>'+
'<div class="explication"><div class="title">Explication</div>un entier au hasard entre -5 et 5 (bornes comprises).</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'random( )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>random(1,2,3,a,b,c)</code></div>'+
'<div class="explication"><div class="title">Explication</div>un item au hasard parmi {1,2,3,a,b,c}</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'shuffle( )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>shuffle(6)</code></div>'+
'<div class="explication"><div class="title">Explication</div>une liste de 6 entiers 1,2,...,6, dans un ordre aléatoire.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'shuffle( , )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>shuffle(a,b,c,d,e)</code></div>'+
'<div class="explication"><div class="title">Explication</div>la liste des lettres {a,b,c,d,e}, dans un ordre aléatoire. <span class="wims_warning">$wims_name_warning</span>, si le premier mot est <span class="tt wims_code_words">even</span> ou <span class="tt wims_code_words">odd</span>, la permutation effectuée sera respectivement paire ou impaire (aussi, cela ne peut être le premier mot de la liste à permuter).</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'randomitem( )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>randomitem(&#92;list)</code></div>'+
'<div class="explication"><div class="title">Explication</div>un item au hasard de la liste &#92;list (items séparés par des virgules).</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'randitem( )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>randitem(+,-)</code></div>'+
'<div class="explication"><div class="title">Explication</div>un signe aléatoire: + ou - ; <span class="tt wims_code_words">randitem(&#92;list)</span> est un item au hasard de la liste <span class="tt wims_code_variable">&#92;list</span> (items séparés par des virgules).</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'randomrow( )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>randomrow(&#92;mat)</code></div>'+
'<div class="explication"><div class="title">Explication</div>une ligne au hasard de la matrice &#92;mat.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	
	}
}