<!-- Automatically generated by bin/oefdoc.pl -->
var oefparm5name= 'Variables prédéfinies';
 var oefparm5= [ '\\reply', '\\choice', '\\step', '\\sc_reply', '\\reply_', '\\help_subject', '\\oef_firstname', '\\oef_lastname', '\\oef_login', '\\oef_now', '\\oef_lang' ];
function oefparm5fun(instruction){
    switch(instruction)
	{
	case '\\reply' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>reply1 reply2 ...</code></div>'+
'<div class="explication"><div class="title">Explication</div>variable contenant la réponse de l\'élève à la question de type <span class="tt wims_code_words">reply</span> numéro 1</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\choice' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>choice1 choice2 ...</code></div>'+
'<div class="explication"><div class="title">Explication</div>variable contenant la réponse de l\'élève à la question de type <span class="tt wims_code_words">choice</span> numéro 1</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\step' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>step</code></div>'+
'<div class="explication"><div class="title">Explication</div>variable donnant le numéro de l\'étape (dans le cas où une commande de type </div>'+
'<div class="explication"><div class="title">Explication</div><span class="tt wims_code_variable">&#92;steps</span> ou <span class="tt wims_code_variable">&#92;nextstep</span> a été introduite).</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\sc_reply' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>sc_reply1 sc_reply2 ...</code></div>'+
'<div class="explication"><div class="title">Explication</div>variable entre 0 et 1 indiquant si la réponse à la question est juste ou non </div>'+
'<div class="explication"><div class="title">Explication</div>(peut avoir des valeurs entre 0 et 1 pour certains types de réponses).</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\reply_' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>reply_1 reply_2 ...</code></div>'+
'<div class="explication"><div class="title">Explication</div>variable contenant la réponse de l\'élève formatée comme elle apparait dans l\'analyse de la réponse </div>'+
'<div class="explication"><div class="title">Explication</div>(à utiliser dans le cas d\'exercices à étapes ou lorsque l\'analyse de réponse n\'est pas affichée).</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\help_subject' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>help_subject</code></div>'+
'<div class="explication"><div class="title">Explication</div>variable contenant l\'identificateur de l\'aide introduite par la méthode spéciale <span class="tt wims_code_words">help</span>.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\oef_firstname' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>oef_firstname</code></div>'+
'<div class="explication"><div class="title">Explication</div>Prénom du participant, par défaut <span class="tt wims_code_words">$name_firstname</span>.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\oef_lastname' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>oef_lastname</code></div>'+
'<div class="explication"><div class="title">Explication</div>Nom du participant, par défaut <span class="tt wims_code_words">$name_lastname</span>.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\oef_login' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>oef_login</code></div>'+
'<div class="explication"><div class="title">Explication</div>Identifiant du participant, par défaut <span class="tt wims_code_words">anonymous</span>.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\oef_now' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>oef_now</code></div>'+
'<div class="explication"><div class="title">Explication</div>Temps sous la forme aaaammjj:hh:mm:ss (20110515.22:19:25)</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\oef_lang' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>oef_lang</code></div>'+
'<div class="explication"><div class="title">Explication</div>Langage du participant ou visiteur (par exemple, <span class="tt wims_code_words">en</span>, <span class="tt wims_code_words">fr</span>, <span class="tt wims_code_words">es</span>)</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	
	}
}