<!-- Automatically generated by bin/oefdoc.pl -->
var oefparm3name= 'Fonctions mathématiques';
 var oefparm3= [ ' evalue( ) ', ' solve( ) ', ' simplify( ) ', ' diff( ) ', ' int( , ) ', ' int( , = .. ) ', ' det( ) ', ' abs( ) ', ' sqrt( ) ', ' binomial( , ) ', ' ceil( ) ', ' floor( ) ', ' rint( ) ', ' e ', ' erf( ) ', ' erfc( ) ', ' Euler ', ' exp( ) ', ' factorial( ) ', ' Inf ', ' gcd( , ) ', ' lcm( , ) ', ' % ', ' max( , ) ', ' min( , ) ', ' lg( ) ', ' lgamma( ) ', ' ln( ) ', ' log2( ) ', ' pow( ) ', ' sgn( ) ', ' PI ', ' sin ', ' acos ', ' sh ', ' Argch ' ];
function oefparm3fun(instruction){
    switch(instruction)
	{
	case ' evalue( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>evalue(x^2+sin(y),x=3,y=4)</code></div>'+
'<div class="explication"><div class="title">Explication</div>évaluation de la fonction x^2+sin(y) en x=3, y=4</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' solve( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>solve(x^3-3*x+1,x=0..1)</code></div>'+
'<div class="explication"><div class="title">Explication</div>la racine simple de x^3-3x+1 entre 0 et 1</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' simplify( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>simplify(x^5*y^3*x^2/y)</code></div>'+
'<div class="explication"><div class="title">Explication</div>expression simplifiée : x<sup>7</sup>y<sup>2</sup></div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' diff( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>diff(sin(x)+cos(y),x)</code></div>'+
'<div class="explication"><div class="title">Explication</div>la dérivée de sin(x)+cos(y) par rapport à x</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' int( , ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>int(x^2+3*x+1,x)</code></div>'+
'<div class="explication"><div class="title">Explication</div>primitive de x^2+3*x+1, le terme constant étant indéterminé</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' int( , = .. ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>int(t^2+3*t+1,t=0..1)</code></div>'+
'<div class="explication"><div class="title">Explication</div>l\'intégrale numérique de x^2+3*x+1, entre 0 et 1</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' det( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>det(&#92;mat)</code></div>'+
'<div class="explication"><div class="title">Explication</div>le déterminant de la matrice &#92;mat</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' abs( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>abs(-3.4)</code></div>'+
'<div class="explication"><div class="title">Explication</div>valeur absolue (equivalent : fabs( ))</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' sqrt( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{a=sqrt(32)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>racine carrée</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' binomial( , ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;integer{a=binomial(9,3)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>le coefficient binomial (pour des coefficients inférieurs à 10^7 sinon utiliser la fonction de pari &#92;text{a=pari(binomial(50,10))}</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' ceil( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{a=ceil(3.4)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>le plus petit entier supérieur</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' floor( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{a=floor(3.4)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>le plus grand entier inférieur</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' rint( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{a=rint(3.4)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>l\'entier le plus proche (equivalent : round( ))</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' e ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{a=e^2}</code></div>'+
'<div class="explication"><div class="title">Explication</div>constante mathématique $m_e ; (equivalent : E)</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' erf( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{a=erf(3.4)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>Fonction erf</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' erfc( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{a=erfc(3.4)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>Fonction erfc</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' Euler ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{a=Euler}</code></div>'+
'<div class="explication"><div class="title">Explication</div>constante d\'Euler : EULER euler</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' exp( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{a=exp(4)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>exponentielle</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' factorial( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;integer{a=factorial(4)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>factorielle</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' Inf ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{a=Inf + 3}</code></div>'+
'<div class="explication"><div class="title">Explication</div>l\'infini</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' gcd( , ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;integer{a=gcd(4,6)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>pgcd de deux entiers</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' lcm( , ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;integer{a=lcm(4,6)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>ppcm de deux entiers</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' % ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;integer{a=5%2}</code></div>'+
'<div class="explication"><div class="title">Explication</div>reste de la division euclidienne</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' max( , ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{a=max(4,6)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>maximum de deux nombres</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' min( , ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{a=gcd(4,6)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>minimum de deux nombres</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' lg( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{a=log10(10^4)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>log en base 10 (equivalent : log10)</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' lgamma( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{a=lgamma(e^(24))}</code></div>'+
'<div class="explication"><div class="title">Explication</div>log de la fonction Gamma</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' ln( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{a=ln(e^4)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>log népérien (equivalent : log)</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' log2( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{a=log2(2^4)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>log en base 2</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' pow( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{a=pow(3,0.6)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>puissance, équivalent à 3^0.6</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' sgn( ) ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;integer{a=sign(-4)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>signe de la valeur (equivalent : sign)</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' PI ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>&#92;real{a=sin(Pi)}</code></div>'+
'<div class="explication"><div class="title">Explication</div>constante mathématique $m_pi, (equivalent : Pi, pi)</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' sin ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>sin(3)</code></div>'+
'<div class="explication"><div class="title">Explication</div>fonctions trigonométriques (autres fonctions : tg tan sec (1/sin) cot cotan cotan ctg csc (1/cos))</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' acos ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>acos(0.5)</code></div>'+
'<div class="explication"><div class="title">Explication</div>fonctions trigonométriques réciproques (autres fonctions : acos arccos acos arcsin asin arctan atan arctg atan)</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' sh ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>sh(4)</code></div>'+
'<div class="explication"><div class="title">Explication</div>fonctions hyperboliques (autres fonctions : sh sinh tanh tanh th ch cosh coth cotanh)</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case ' Argch ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>Argch(4)</code></div>'+
'<div class="explication"><div class="title">Explication</div>fonctions hyperboliques réciproques (autres fonctions : Argch acosh argch Argsh asinh argsh Argth atanh argth)</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	
	}
}